// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAqBo25O0mZDQMC60S9XtpulhbduXlWIDE",
      authDomain: "sweetmeter-6e3e3.firebaseapp.com",
      projectId: "sweetmeter-6e3e3",
      storageBucket: "sweetmeter-6e3e3.firebasestorage.app",
      messagingSenderId: "685238501821",
      appId: "1:685238501821:web:a2491b14385e870dad12d4",
      measurementId: "G-9MXR23B9PF");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGBNi0ptJBFqnEAOnzbf7tuJmZYoIvcM',
    appId: '1:685238501821:android:e7179e32bd4beb4dad12d4',
    messagingSenderId: '685238501821',
    projectId: 'sweetmeter-6e3e3',
    storageBucket: 'sweetmeter-6e3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYrIY1T8VOsYbwhk-tbcLm01KQ6XpoTXI',
    appId: '1:685238501821:ios:2889982703950419ad12d4',
    messagingSenderId: '685238501821',
    projectId: 'sweetmeter-6e3e3',
    storageBucket: 'sweetmeter-6e3e3.firebasestorage.app',
    iosClientId:
    '685238501821-uj1bu14n8ror5v7apgu5hfvd5tieu7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweetmeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYrIY1T8VOsYbwhk-tbcLm01KQ6XpoTXI',
    appId: '1:685238501821:ios:2889982703950419ad12d4',
    messagingSenderId: '685238501821',
    projectId: 'sweetmeter-6e3e3',
    storageBucket: 'sweetmeter-6e3e3.firebasestorage.app',
    iosClientId:
    '685238501821-uj1bu14n8ror5v7apgu5hfvd5tieu7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweetmeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqBo25O0mZDQMC60S9XtpulhbduXlWIDE',
    appId: '1:685238501821:web:63105981cc3e8dc3ad12d4',
    messagingSenderId: '685238501821',
    projectId: 'sweetmeter-6e3e3',
    authDomain: 'sweetmeter-6e3e3.firebaseapp.com',
    storageBucket: 'sweetmeter-6e3e3.firebasestorage.app',
    measurementId: 'G-C7W71C1SK8',
  );
}
